- name: Configure and install HAProxy,create certificate with certbot , install and configure ip tables
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: install HAProxy
      apt:
        name: haproxy
        state: present
    - name: configure HAProxy
      template: 
         src: /etc/haproxy/haproxy.cfg
         dest: /etc/haproxy/haproxy.cfg
      notify: restart HAProxy
    - name: Install and configure IPtables
      apt:
        name: iptables-persistent
        state: present
      become: yes

    - name: Allow SSH connections
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
      become: yes

    - name: Allow HTTP connections (port 80)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
      become: yes

    - name: Allow HTTPS connections (port 443)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
      become: yes

    - name: Ensure IPtables rules are saved and applied on boot
      service:
        name: iptables
        enabled: yes
        state: started
      become: yes

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      become: yes  
    - name: restart HAProxy
      service: 
        name: haproxy
        state: restarted


