- name: configure and install nginx machineC , install and configure ip tables
  hosts: machineC
  become: true
  vars_files:
    - passwords.yml
  vars:
    ansible_become_pass: "{{ host2_password }}"
  tasks:
    - name: install nginx
      apt:
           name: nginx
           state: present
    - name: configure nginx
      template: 
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx  
    - name: Install and configure IPtables
      apt:
        name: iptables-persistent
        state: present

    - name: Allow SSH connections
      iptables:
         chain: INPUT
         protocol: tcp
         destination_port: 22
         jump: ACCEPT
      become: yes

    - name: Allow HTTP connections (port 80)
      iptables:
         chain: INPUT
         protocol: tcp
         destination_port: 80
         jump: ACCEPT
      become: yes

    - name: Allow HTTPS connections (port 443)
      iptables:
         chain: INPUT
         protocol: tcp
         destination_port: 443
         jump: ACCEPT
      become: yes

    - name: Ensure IPtables rules are saved and applied on boot
      service:
         name: iptables
         enabled: yes
         state: started
      become: yes

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      become: yes
    - name: restart nginx
      service: 
         name: nginx
         state: restarted 
