- name: configure and install nginx machineC , install and configure ip tables
  hosts: machineC
  become: true
  tasks:
    - name: install nginx
      apt:
           name: nginx
           state: present
    - name: Configure Nginx
      copy:
        content: |
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;

          events {
              worker_connections 768;
          }

          http {

              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;

              include /etc/nginx/mime.types;
              default_type application/octet-stream;


              ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
              ssl_prefer_server_ciphers on;

  

              access_log /var/log/nginx/access.log;
              error_log /var/log/nginx/error.log;
              server {
                  listen 8080;
                  server_name localhost;

                  location / {
                      root /var/www/html;
                      index index.html;
                  }
              }
          }
        dest: /etc/nginx/nginx.conf
      notify: restart nginx  
    - name: Install and configure IPtables
      apt:
        name: iptables-persistent
        state: present

    - name: Allow SSH connections
      iptables:
         chain: INPUT
         protocol: tcp
         destination_port: 22
         jump: ACCEPT
      become: yes

    - name: Allow HTTP connections (port 8080)
      iptables:
         chain: INPUT
         protocol: tcp
         destination_port: 8080
         jump: ACCEPT
      become: yes

    - name: Allow HTTPS connections (port 443)
      iptables:
         chain: INPUT
         protocol: tcp
         destination_port: 443
         jump: ACCEPT
      become: yes

    - name: Ensure IPtables rules are saved and applied on boot
      service:
         name: iptables
         enabled: yes
         state: started
      become: yes

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      become: yes
    - name: restart nginx
      service: 
         name: nginx
         state: restarted 
